apiVersion: apps/v1
kind: Deployment
metadata:
  name: website
  labels:
    app: website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: website
  template:
    metadata:
      labels:
        app: website
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 101
        runAsGroup: 101
      containers:
        - name: website
          image: lukadimnik/website:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - { name: nginx-cache, mountPath: /var/cache/nginx }
            - { name: nginx-run,   mountPath: /var/run }
      volumes:
        - { name: nginx-cache, emptyDir: {} }
        - { name: nginx-run,   emptyDir: {} }
---
apiVersion: v1
kind: Service
metadata:
  name: website
spec:
  type: ClusterIP 
  selector:
    app: website
  ports:
    - port: 80
      targetPort: 80
